// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.Api.Data;

#nullable disable

namespace Users.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717190029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.Api.Models.AndonEventModel", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvent"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdFailure")
                        .HasColumnType("integer");

                    b.Property<int>("IdMachine")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEvent");

                    b.ToTable("AndonEvents");
                });

            modelBuilder.Entity("Users.Api.Models.AreaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AreaModels");
                });

            modelBuilder.Entity("Users.Api.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("AreaId1")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Users.Api.Models.Machine", b =>
                {
                    b.Property<int>("IdMachine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMachine"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdWorkStation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkStationIdWorkStation")
                        .HasColumnType("integer");

                    b.HasKey("IdMachine");

                    b.HasIndex("IdWorkStation");

                    b.HasIndex("WorkStationIdWorkStation");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Users.Api.Models.ProduccionModel", b =>
                {
                    b.Property<int>("IdProduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduccion"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdArea")
                        .HasColumnType("integer");

                    b.Property<int>("IdLine")
                        .HasColumnType("integer");

                    b.Property<int>("IdMachine")
                        .HasColumnType("integer");

                    b.Property<int>("IdModel")
                        .HasColumnType("integer");

                    b.Property<int>("IdStation")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("ProductionDowntime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ProductionTime")
                        .HasColumnType("interval");

                    b.Property<int>("QuantityProducedNG")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityProducedOK")
                        .HasColumnType("integer");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("integer");

                    b.HasKey("IdProduccion");

                    b.HasIndex("UserIdUser");

                    b.ToTable("ProduccionModels");
                });

            modelBuilder.Entity("Users.Api.Models.UserModel", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Users.Api.Models.WorkStation", b =>
                {
                    b.Property<int>("IdWorkStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkStation"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdLine")
                        .HasColumnType("integer");

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdWorkStation");

                    b.HasIndex("IdLine");

                    b.HasIndex("LineId");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("Users.Api.Models.Line", b =>
                {
                    b.HasOne("Users.Api.Models.AreaModel", null)
                        .WithMany("Lines")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Users.Api.Models.AreaModel", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Users.Api.Models.Machine", b =>
                {
                    b.HasOne("Users.Api.Models.WorkStation", null)
                        .WithMany("Machines")
                        .HasForeignKey("IdWorkStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Users.Api.Models.WorkStation", "WorkStation")
                        .WithMany()
                        .HasForeignKey("WorkStationIdWorkStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkStation");
                });

            modelBuilder.Entity("Users.Api.Models.ProduccionModel", b =>
                {
                    b.HasOne("Users.Api.Models.UserModel", "User")
                        .WithMany("ProduccionModels")
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Users.Api.Models.WorkStation", b =>
                {
                    b.HasOne("Users.Api.Models.Line", null)
                        .WithMany("WorkStations")
                        .HasForeignKey("IdLine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Users.Api.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Users.Api.Models.AreaModel", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Users.Api.Models.Line", b =>
                {
                    b.Navigation("WorkStations");
                });

            modelBuilder.Entity("Users.Api.Models.UserModel", b =>
                {
                    b.Navigation("ProduccionModels");
                });

            modelBuilder.Entity("Users.Api.Models.WorkStation", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
